{
 "title": "IOT TELEMETRY",
 "description": "ALL DATA IN IOT TELEMETRY TABLE",
 "time": { "from": "2020-07-12T00:00:00.000Z", "to": "2020-07-12T02:59:59.000Z" },
 "panels": [
  { "title": "Comparison Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Monoxide Comparison Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  co\nFROM iot_telemetry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature Comparison Over Time",
   "type": "timeseries",
   "description": "celsius ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  temp\nFROM iot_telemetry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Humidity Comparison Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  humidity\nFROM iot_telemetry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Liquid Petroleum Gas Comparison Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  lpg\nFROM iot_telemetry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Smoke Comparison Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  smoke\nFROM iot_telemetry\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Motion Comparison Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  motion\nFROM iot_telemetry\nWHERE\n  motion = 1\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Light Comparison Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  device AS metric,\n  light\nFROM iot_telemetry\nWHERE\n  light = 1\nORDER BY 1,2"
    }
   ]
  }
 ]
}